import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../app/components/ui/Header/Header'
import { LoginForm } from '../app/components/ui/Header/LoginForm/LoginForm'



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

    </div>
  )
}

export default Home
